version: "3.9"
services:
  database:
    image: "postgres:14.1"
    environment:
      POSTGRES_DB: ws-dj-backend
      POSTGRES_USER: ws-dj-admin
      POSTGRES_PASSWORD: ws-dj-admin!
    ports:
      - "5432:5432"
    volumes:
      - "jk-ws-database:/var/lib/postgresql/data"
  web:
    build:
      context: src
    working_dir: /ws-dj
    command: ./bin/run.sh
    depends_on:
      - database
    volumes:
      - ./src:/ws-dj
  nginx:
    ports:
      - "80:80/tcp"
    links:
      - web
    image: "nginx:1.20.2"
    volumes:
      - type: bind
        read_only: true
        source: ./nginx/dev/
        target: /etc/nginx
      - type: bind
        read_only: true
        source: ./nginx/www/
        target: /var/www/
    depends_on:
      - web
volumes:
  jk-ws-database:
    external: true