# Generated by Django 4.0 on 2022-02-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userfriend',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='userfriend',
            constraint=models.UniqueConstraint(fields=('user_from', 'user_to'), name='unique_friends_constraint'),
        ),
    ]
