# Generated by Django 4.0 on 2022-02-03 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.CharField(max_length=128)),
                ('user_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_recommendation_from', to='auth.user')),
                ('user_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_recommendation_to', to='auth.user')),
            ],
            options={
                'verbose_name': 'song recommendations',
                'verbose_name_plural': 'song recommendations',
            },
        ),
    ]
