# Generated by Django 4.0 on 2022-10-30 20:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0003_trackrecommendation_has_listened'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackrecommendation',
            name='rating',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
