# Generated by Django 4.0 on 2023-06-25 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouptrack',
            name='listened',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='grouptrack',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='groups.group'),
        ),
    ]
